site_name: obcam
site_description: Flight camera module and program for the OB team rocket in NSE 2022.
site_url: https://FROM-THE-EARTH.github.io/obcam/

docs_dir: docs
repo_url: https://github.com/FROM-THE-EARTH/obcam/
repo_name: obcam
copyright: Copyright &copy; FROM THE EARTH

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
  palette:
    primary: grey

nav:
  - Home: index.md
  - Setup: setup.md
  - FlightCamera: flightcam.md
  - Setting: setting.md
  - Scripts: scripts.md
  - Checklist: checklist.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FROM-THE-EARTH/obcam/

plugins:
  - search
